import { Project } from './types';

export const projects: Project[] = [
  {
    id:'4lkj34224',
    title: 'Aphex Planner',
    src: 'images.webp',
    color: '#dbeafe',
    url: 'https://app.aphex.co/',
    tech:['nextJs', 'Framer', 'yaawoo'],
    about:'somthin in about yaawoon',
    role: 'Fullstack Developer',

  },
  {
    id:'4lkj342dfd',
    title: 'Aphex Field',
    src: 'field-app.webp',
    color: '#ddd6fe',
    url: 'https://app.aphex.co/',
    tech:['nextJs', 'Framer', 'yaawoo'],
    about:'somthin in about yaawoo',
    role: 'Fullstack Developer',
  },
  {
    id:'4lkj342wf33',
    title: 'Aphex Publication',
    src: 'publication-app.webp',
    color: '#fae8ff',
    url: 'https://app.aphex.co/',
    tech:['nextJs', 'Framer', 'yaawoo'],
    about:'somthin in about yaawoo',
    role: 'Fullstack Developer',
  },
  {
    id:'4lkj34223rf',
    title: 'Spoken',
    src: 'spoken.webp',
    color: '#fee2e2',
    url: 'https://www.spoken.io/',
    tech:['nextJs', 'Framer', 'yaawoo'],
    about:'somthin in about yaawoo',
    role: 'Fullstack Developer',
  },
  {
    id:'4lkj3423f33',
    title: 'Topography Health',
    src: 'topo.webp',
    color: '#dbeafe',
    url: 'https://www.jointopo.com/',
    tech:['nextJs', 'Framer', 'yaawoo'],
    about:'somthin in about yaawoo',
    role: 'Backend Developer',
  },
  {
    id:'4lkj3425f23',
    title: 'SRI Big Data',
    src: 'bigdata.webp',
    color: '#ddd6fe',
    url: 'https://bigdata.sri.com.sg',
    tech:['nextJs', 'Framer', 'yaawoo'],
    about:'somthin in about yaawoo',
    role: 'Frontend Developer',
  },
  {
    id:'4lkj34256hgf',
    title: 'Mathgame',
    src: 'mathgame.png',
    color: '#ffedd5',
    url: 'https://mathgame.dalelarroder.com/',
    tech:['nextJs', 'Framer', 'yaawoo'],
    about:'somthin in about yaawoo',
    role: 'Frontend Developer',
  },
  {
    id:'4lkj342dvd53',
    title: 'Snakegame',
    src: 'snakegame.png',
    color: '#ecfccb',
    url: 'https://snakegame.dalelarroder.com/',
    tech:['nextJs', 'Framer', 'yaawoo'],
    about:'somthin in about yaawoo',
    role: 'Frontend Developer',
  },
];

export const color: string[] = [
  "#F59E0B",
  "#65A30D",
  "#EA580C",
  "#C026D3",
  "#14B8A6",
  "#E11D48",
  "#e09f3e",
  "#8338ec",
  "#ff9f1c",
  "#003d5b",
];