import { Project } from './types';

export const projects: Project[] = [
  {
    id: '4lkj34224',
    title: 'Events Lab 🔖',
    src: 'EventsLAB.png',
    color: '#dbeafe',
    url: 'https://eventlab.netlify.app/',
    tech: ['React', 'Firebase'],
    about: 'Find the Latest events near you and Book it with dashoard',
    role: 'Fullstack',

  },
  {
    id: '4lkj342dfd',
    title: 'EatingOut 🍴',
    src: 'eatingOut.png',
    color: '#ddd6fe',
    url: 'https://eatingout-reactapp.netlify.app/',
    tech: ['React', 'Framer', 'Firebase'],
    about: 'Resturent App order food and track the file with dashbaord',
    role: 'Fullstack',
  },
  {
    id: '4lkj342wf33',
    title: 'Trend Blend 🛒',
    src: 'TrendBlend.png',
    color: '#fae8ff',
    url: 'https://trendblend.netlify.app/',
    tech: ['React', 'Node.js', 'Express', "Framer", "MongoDB", "RestAPI"],
    about: 'Ecommerece App with CMS',
    role: 'FullStack',
  },
  {
    id: '4lkj34223rf',
    title: 'Url Shortner 🔗',
    src: 'ShortUrl.png',
    color: '#fee2e2',
    url: 'https://learnwithfaizan.netlify.app/',
    tech: ['React', "EJS", "Node.js", 'Express', "MongoDB", "RestAPI", 'Render', 'vercel'],
    about: 'You can short your URLS',
    role: 'Backend ',
  },
  {
    id: '4lkj3423f33',
    title: 'FileLinker 📩',
    src: 'fileLinker.png',
    color: '#dbeafe',
    url: 'https://file-linker.vercel.app/',
    tech: ['React', 'Firebase', 'ChakraUi','Bootstrap','dayjs'],
    about: 'A FileSharing app to share your files with others',
    role: 'FullStack',
  },
  {
    id: '4lkj3425f23',
    title: 'Threads Clone 🧑‍💻',
    src: 'threads.png',
    color: '#ddd6fe',
    url: 'https://threads-clone-ten-psi.vercel.app/',
    tech: ['NextJs-13', 'TypeScript','Clerk Auth', 'Uploadthing','TailwindCss'],
    about: 'A social media application where you can share your moments',
    role: 'FullStack',
  },
  {
    id: '4lkj34256hgf',
    title: 'Sticky-Wall 🧱',
    src: 'stickyWall.png',
    color: '#ffedd5',
    url: 'https://sticky-wall.vercel.app/',
    tech: ['ReactJs', 'antd', 'Bootstrap', 'firebase'],
    about: 'A Task Management System helps you manage your tasks',
    role: 'Frontend',
  },
  {
    id: '4lkj34256hgf',
    title: 'Todo App 📝',
    src: 'todo.png',
    color: '#ffedd5',
    url: 'https://my-todo-49.web.app/',
    tech: ['ReactJs','Bootstrap', 'firebase'],
    about: 'A Todo app my first Firebase application',
    role: 'Backend',
  },
  {
    id: '4lkj342dvd53',
    title: 'Snakegame',
    src: 'snakegame.png',
    color: '#ecfccb',
    url: 'https://snakegame.dalelarroder.com/',
    tech: ['nextJs', 'Framer', 'yaawoo'],
    about: 'somthin in about yaawoo',
    role: 'Frontend Developer',
  },
];

export const color: string[] = [
  "#F59E0B",
  "#65A30D",
  "#EA580C",
  "#C026D3",
  "#14B8A6",
  "#E11D48",
  "#e09f3e",
  "#8338ec",
  "#ff9f1c",
  "#003d5b",
];