import { Project } from './types';

export const projects: Project[] = [
  {
    id: '4lkj34224',
    title: 'Events Lab',
    src: 'EventsLAB.png',
    color: '#dbeafe',
    url: 'https://eventlab.netlify.app/',
    tech: ['React', 'Firebase'],
    about: 'Find the Latest events near you and Book it with dashoard',
    role: 'Fullstack Developer',

  },
  {
    id: '4lkj342dfd',
    title: 'eatingout',
    src: 'eatingOut.png',
    color: '#ddd6fe',
    url: 'https://eatingout-reactapp.netlify.app/',
    tech: ['React', 'Framer', 'Firebase'],
    about: 'Resturent App order food and track the file with dashbaord',
    role: 'Fullstack Developer',
  },
  {
    id: '4lkj342wf33',
    title: 'Trend Blend',
    src: 'TrendBlend.png',
    color: '#fae8ff',
    url: 'https://trendblend.netlify.app/',
    tech: ['React', 'Node.js', 'Express', "Framer", "MongoDB", "RestAPI"],
    about: 'Ecommerece App with CMS',
    role: 'Fullstack Developer',
  },
  {
    id: '4lkj34223rf',
    title: 'Url Shortner',
    src: 'ShortUrl.png',
    color: '#fee2e2',
    url: 'https://learnwithfaizan.netlify.app/',
    tech: ['React', "EJS", "Node.js", 'Express', "MongoDB", "RestAPI", 'Render', 'vercel'],
    about: 'You can short your URLS',
    role: 'Fullstack Developer',
  },
  {
    id: '4lkj3423f33',
    title: 'Topography Health',
    src: 'topo.webp',
    color: '#dbeafe',
    url: 'https://www.jointopo.com/',
    tech: ['nextJs', 'Framer', 'yaawoo'],
    about: 'somthin in about yaawoo',
    role: 'Backend Developer',
  },
  {
    id: '4lkj3425f23',
    title: 'SRI Big Data',
    src: 'bigdata.webp',
    color: '#ddd6fe',
    url: 'https://bigdata.sri.com.sg',
    tech: ['nextJs', 'Framer', 'yaawoo'],
    about: 'somthin in about yaawoo',
    role: 'Frontend Developer',
  },
  {
    id: '4lkj34256hgf',
    title: 'Mathgame',
    src: 'mathgame.png',
    color: '#ffedd5',
    url: 'https://mathgame.dalelarroder.com/',
    tech: ['nextJs', 'Framer', 'yaawoo'],
    about: 'somthin in about yaawoo',
    role: 'Frontend Developer',
  },
  {
    id: '4lkj342dvd53',
    title: 'Snakegame',
    src: 'snakegame.png',
    color: '#ecfccb',
    url: 'https://snakegame.dalelarroder.com/',
    tech: ['nextJs', 'Framer', 'yaawoo'],
    about: 'somthin in about yaawoo',
    role: 'Frontend Developer',
  },
];

export const color: string[] = [
  "#F59E0B",
  "#65A30D",
  "#EA580C",
  "#C026D3",
  "#14B8A6",
  "#E11D48",
  "#e09f3e",
  "#8338ec",
  "#ff9f1c",
  "#003d5b",
];